@startuml

package Game-Scene [[vscode://file/./TestCases/BaseProject/Game.tscn]] {
	
class Game  {
	[[vscode://file/{CurrentDirectory}Game/Game.cs ScriptFile]]
--
[[vscode://file/{CurrentDirectory}Game/Game.cs:22 GameLogic]] - [[vscode://file/{CurrentDirectory}TestCases/BaseProject/Logic/GameLogic.cs Script]]
	[[vscode://file/{CurrentDirectory}Game/Game.cs:21 GameRepo]] - [[vscode://file/{CurrentDirectory}TestCases/BaseProject/Domain/GameRepo.cs Script]]
}

	
class GameRepo  {
	[[vscode://file/{CurrentDirectory}TestCases/BaseProject/Domain/GameRepo.cs ScriptFile]]
--
+ [[vscode://file/{CurrentDirectory}TestCases/BaseProject/Domain/GameRepo.cs:15 Instantiator]]
--
[[vscode://file/{CurrentDirectory}TestCases/BaseProject/Domain/GameRepo.cs:17 CreateInstantiator()]]
}

	Game::GameRepo --> GameRepo
}

@enduml