@startuml

package Game-Scene [[vscode://file/{ProjectDirectory}TestCases/BaseProject_VSCode/Game.tscn]] {
	
class Game  {
	[[vscode://file/{ProjectDirectory}Game/Game.cs ScriptFile]]
--
[[vscode://file/{ProjectDirectory}Game/Game.cs:22 GameLogic]] - [[vscode://file/{ProjectDirectory}TestCases/BaseProject_VSCode/Logic/GameLogic.cs Script]]
	[[vscode://file/{ProjectDirectory}Game/Game.cs:21 GameRepo]] - [[vscode://file/{ProjectDirectory}TestCases/BaseProject_VSCode/Domain/GameRepo.cs Script]]
}

	
class GameRepo  {
	[[vscode://file/{ProjectDirectory}TestCases/BaseProject_VSCode/Domain/GameRepo.cs ScriptFile]]
--
+ [[vscode://file/{ProjectDirectory}TestCases/BaseProject_VSCode/Domain/GameRepo.cs:15 Instantiator]]
--
[[vscode://file/{ProjectDirectory}TestCases/BaseProject_VSCode/Domain/GameRepo.cs:17 CreateInstantiator()]]
}

	Game::GameRepo --> GameRepo
}

@enduml