@startuml

package Game-Scene [[../../TestCases/HasDependency/Game.tscn]] {
	
class Game  {
	[[../../Game/Game.cs ScriptFile]]
	[Provisions]
	[[../../Game/Game.cs:15 IGameRepo]]
--
World - [[../../World/World.cs Script]]
	[[../../Game/Game.cs:22 GameLogic]] - [[../../TestCases/HasDependency/Logic/GameLogic.cs Script]]
	[[../../Game/Game.cs:21 GameRepo]] - [[../../TestCases/HasDependency/Domain/GameRepo.cs Script]]
}

	
class World  {
	[[../../World/World.cs ScriptFile]]
	[Dependencies]
	[[../../World/World.cs:19 GameRepo]] - [[../../TestCases/HasDependency/Domain/GameRepo.cs Script]]
}

	
class GameRepo  {
	[[../../TestCases/HasDependency/Domain/GameRepo.cs ScriptFile]]
--
+ [[../../TestCases/HasDependency/Domain/GameRepo.cs:15 Instantiator]]
--
[[../../TestCases/HasDependency/Domain/GameRepo.cs:17 CreateInstantiator()]]
}

	Game::World --> World
	Game::GameRepo --> GameRepo
}

@enduml