@startuml

package Game-Scene [[../../TestCases/ShowAllProperties/Game.tscn]] {
	
class Game  {
	[[../../Game/Game.cs ScriptFile]]
	[Provisions]
	[[../../Game/Game.cs:15 IGameRepo]]
--
+ [[../../Game/Game.cs:23 AppBinding]]
	+ [[../../Game/Game.cs:22 GameLogic]] - [[../../TestCases/ShowAllProperties/Logic/GameLogic.cs Script]]
	+ [[../../Game/Game.cs:21 GameRepo]] - [[../../TestCases/ShowAllProperties/Domain/GameRepo.cs Script]]
}

	
class GameRepo  {
	[[../../TestCases/ShowAllProperties/Domain/GameRepo.cs ScriptFile]]
--
+ [[../../TestCases/ShowAllProperties/Domain/GameRepo.cs:15 Instantiator]]
--
[[../../TestCases/ShowAllProperties/Domain/GameRepo.cs:17 CreateInstantiator()]]
}

	Game::GameRepo --> GameRepo
}

@enduml